site_name: Amoothei-VDI
docs_dir: doc
pages:
- Overview: 'index.md'
- 'VM rollout':
        - 'VM rollout tools': amoothei-vm-rollout.md
        - 'Installing amoothei-vm-rollout': amoothei-vm-rollout-install.md
        - 'Configuring virtual rooms': amoothei-vm-rollout-config.md
        - stateless_and_snapshot_features.md
        - 'Quality control after rollout': quality_control.md
        - 'Windows Unattended Setup': Autounattend.md
        - 'Windows Goldimage': Goldimage.md
- 'Thinclients':
        - 'Setting up an infrastructure server for thinclients': amoothei-infrastructure-server.md
        - 'Rolling out Thinclients using Kickstart': amoothei-tc-kickstart.md
        - 'Managing Thinclients': amoothei-tc-tools.md
        - 'VDI software running on Thinclients': amoothei-tc-connectspice.md
        - 'USB Redirect: avoiding USB Reset': libusbredir-patching.md
- 'Misc':
        - Compatibility.md
        - 'Payload injection': sftp-floppy-upload.md
        - 'Workarounds': workaround_os.md

markdown_extensions:
    - toc:
        permalink: 
    - admonition:
